// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// `prisma generate` does not open a DB connection, but Prisma 7 still evaluates this config
// and throws if the variable is missing. Use a harmless placeholder when unset during build.
const databaseUrl =
   process.env.DATABASE_URL ??
   "postgresql://placeholder:placeholder@127.0.0.1:5432/placeholder?schema=public";

// For migrations, Prisma needs a direct (non-pooled) connection to acquire advisory locks.
// Neon direct URL is the same as the pooler URL but without "-pooler" in the hostname.
// Set DIRECT_DATABASE_URL in Vercel env vars to the direct connection string.
// Falls back to DATABASE_URL if not set (works for local dev).
const directUrl =
   process.env.DIRECT_DATABASE_URL ??
   databaseUrl;

export default defineConfig({
   schema: "prisma/schema.prisma",
   migrations: {
      path: "prisma/migrations",
   },
   datasource: {
      url: databaseUrl,
      directUrl,
   },
});
