// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// `prisma generate` does not open a DB connection, but Prisma 7 still evaluates this config
// and `env("DATABASE_URL")` throws if the variable is missing. Vercel builds often do not inject
// `DATABASE_URL` until runtime, so use a harmless placeholder when unset (same idea as the Dockerfile).
const databaseUrl =
   process.env.DATABASE_URL ??
   "postgresql://placeholder:placeholder@127.0.0.1:5432/placeholder?schema=public";

export default defineConfig({
   schema: "prisma/schema.prisma",
   migrations: {
      path: "prisma/migrations",
   },
   datasource: {
      url: databaseUrl,
   },
});


